# Generated by Django 2.2.3 on 2020-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
