# Generated by Django 2.2.3 on 2020-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200811_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='position',
            field=models.CharField(default='Mensajero', max_length=20, verbose_name='Cargo'),
        ),
    ]
