# Generated by Django 2.2.3 on 2020-08-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='% Descuento Mensual'),
        ),
    ]
