# Generated by Django 2.2.3 on 2020-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200816_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='% Descuento Mensual'),
        ),
    ]
