# Generated by Django 2.2.3 on 2020-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200827_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attending',
            field=models.CharField(max_length=100, verbose_name='Acudiente'),
        ),
    ]
