# Generated by Django 2.2.3 on 2020-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200828_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono 2'),
        ),
    ]
