# Generated by Django 2.2.3 on 2020-09-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200906_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
