# Generated by Django 2.2.3 on 2021-04-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nota'),
        ),
    ]
