# Generated by Django 2.2.3 on 2022-01-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210422_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_retiro',
            field=models.DateField(default=None, verbose_name='Fecha de Retiro'),
        ),
    ]
