# Generated by Django 2.2.3 on 2022-01-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220128_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro'),
        ),
    ]
