# Generated by Django 2.2.3 on 2022-01-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220128_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=1, max_length=20, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='attending_document',
            field=models.CharField(default=1, max_length=20, verbose_name='No. de Documento Acudiente'),
            preserve_default=False,
        ),
    ]
