# Generated by Django 2.2.3 on 2022-02-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220128_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attending_document',
            field=models.CharField(max_length=100, verbose_name='No. de Documento Acudiente'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=100, verbose_name='No. de Documento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Nota'),
        ),
    ]
