# Generated by Django 2.2.3 on 2020-08-18 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='values',
            new_name='value',
        ),
    ]
