# Generated by Django 2.2.3 on 2020-08-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200817_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='concept',
            new_name='description',
        ),
    ]
