# Generated by Django 2.2.3 on 2020-08-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200820_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Concepto'),
        ),
    ]
