# Generated by Django 2.2.3 on 2020-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200825_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia'),
        ),
    ]
