# Generated by Django 2.2.3 on 2020-10-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_compromisepay'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisepay',
            name='document',
            field=models.CharField(default=1, max_length=100, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compromisepay',
            name='person_charge',
            field=models.CharField(default=1, max_length=100, verbose_name='Responsable'),
            preserve_default=False,
        ),
    ]
