# Generated by Django 2.2.3 on 2020-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20201022_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisepay',
            name='month_owed',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Mensualidades'),
            preserve_default=False,
        ),
    ]
