# Generated by Django 2.2.3 on 2021-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='abbreviation',
            field=models.CharField(default='00', max_length=4, verbose_name='Abreviacion'),
        ),
    ]
